  Vagrant.configure("2") do |config|

    config.vm.define "machine" do |machine|
      machine.vm.box = "generic/rocky8"
      machine.vm.network :private_network, ip:"192.168.0.20"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "machine"
        vb.memory = 1024
        vb.cpus = 2
      end

      machine.vm.provision "shell", path: "ansible-provisioning.sh"
    end
  end